pet 28 jun 2024 10:25:10 CEST
Traceback (most recent call last):
  File "/home/dis/miniconda3/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/home/dis/miniconda3/lib/python3.12/site-packages/conda/__init__.py", line 6, in <module>
    from json import JSONEncoder
  File "/home/dis/miniconda3/lib/python3.12/json/__init__.py", line 107, in <module>
    from .encoder import JSONEncoder
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1124, in get_code
  File "<frozen importlib._bootstrap_external>", line 753, in _compile_bytecode
KeyboardInterrupt
pet 28 jun 2024 10:29:16 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
Brio channel: 4
Brio channel: 2
StreamCam channel: 0
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.018] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@61.018] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 84, in captureImages
    frames = self.pipeline.wait_for_frames(10000)
RuntimeError: Frame didn't arrive within 10000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 84, in captureImages
    frames = self.pipeline.wait_for_frames(10000)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 28 jun 2024 10:33:21 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
Brio channel: 4
Brio channel: 2
StreamCam channel: 0
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.018] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@61.018] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.337] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video12): select() timeout.
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 84, in captureImages
    frames = self.pipeline.wait_for_frames(10000)
RuntimeError: Frame didn't arrive within 10000
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 28 jun 2024 14:11:30 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Brio channel: 4
Brio channel: 2
StreamCam channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.030] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@61.030] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
