pet 19 jul 2024 13:37:50 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 4
Brio channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.049] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.049] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 19 jul 2024 13:42:58 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.054] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video5): can't open camera by index
[ WARN:0@61.054] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.256] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 19 jul 2024 13:47:55 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 10
Brio channel: 8
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.052] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.052] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 19 jul 2024 14:02:43 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.080] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video5): can't open camera by index
[ WARN:0@61.080] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.273] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
čet 25 jul 2024 10:10:43 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.076] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video5): can't open camera by index
[ WARN:0@61.076] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
WARNING:flirpy.camera.lepton:Failed to capture image
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
čet 25 jul 2024 14:22:41 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.032] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video5): can't open camera by index
[ WARN:0@61.032] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 26 jul 2024 13:08:33 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 4
Brio channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.048] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.048] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pon 02 sep 2024 12:33:18 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
Brio channel: 12
Brio channel: 10
StreamCam channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.531] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.531] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 104, in captureImages
    with h5py.File(
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/h5py/_hl/files.py", line 241, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 122, in h5py.h5f.create
FileNotFoundError: [Errno 2] Unable to synchronously create file (unable to open file: name = 'installers/data_collection/data/realsense/depth/dis_0_2024-09-02$12-38-07-357544.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  5101 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
pon 02 sep 2024 14:12:58 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 10
Brio channel: 8
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.021] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video7): can't open camera by index
[ WARN:0@61.021] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.335] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video6): select() timeout.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
/home/dis/trust-me-setup/installers/data_capture/microphone.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  recording_np = np.concatenate(np.array(self.recording), axis=0)
Process Process-1:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 79, in record
    self.save_recording()
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 83, in save_recording
    recording_np = np.concatenate(np.array(self.recording), axis=0)
RuntimeError: Inconsistent object during array creation? Content of sequences changed (length inconsistent).
/home/dis/trust-me-setup/startup_script.sh: line 62: Run: command not found
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  3286 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
Done
čet 05 sep 2024 07:12:38 CEST
conda 24.4.0
Video now available. Starting script...
StreamCam channel: 12
Brio channel: 10
Brio channel: 8
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@60.988] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video7): can't open camera by index
[ WARN:0@60.988] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.298] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video6): select() timeout.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Process-1:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 79, in record
    self.save_recording()
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 83, in save_recording
    recording_np = np.concatenate(np.array(self.recording, dtype=object), axis=0)
RuntimeError: Inconsistent object during array creation? Content of sequences changed (length inconsistent).
/home/dis/trust-me-setup/startup_script.sh: line 54: Run: command not found
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  3165 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
Done
čet 05 sep 2024 07:34:15 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 12
Brio channel: 10
StreamCam channel: 0
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.012] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video3): can't open camera by index
[ WARN:0@61.012] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Process-1:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 79, in record
    self.save_recording()
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 83, in save_recording
    recording_np = np.concatenate(np.array(self.recording, dtype=object), axis=0)
RuntimeError: Inconsistent object during array creation? Content of sequences changed (length inconsistent).
Process Process-3:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/thermal.py", line 85, in captureImages
    frame = self.camera.grab()  # .astype(np.float32)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/flirpy/camera/lepton.py", line 158, in grab
    res, image = self.cap.read()
KeyboardInterrupt
/home/dis/trust-me-setup/startup_script.sh: line 54: Run: command not found
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  3952 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
Done
čet 05 sep 2024 07:50:37 CEST
conda 24.4.0
Video now available. Starting script...
StreamCam channel: 6
Brio channel: 4
Brio channel: 2
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.024] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.024] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@72.053] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Process-1:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 79, in record
    self.save_recording()
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 83, in save_recording
    recording_np = np.concatenate(np.array(self.recording, dtype=object), axis=0)
RuntimeError: Inconsistent object during array creation? Content of sequences changed (length inconsistent).
/home/dis/trust-me-setup/startup_script.sh: line 54: Run: command not found
Done
pon 09 sep 2024 07:09:35 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 10
Brio channel: 8
StreamCam channel: 0
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@60.928] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@60.928] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Process-1:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 79, in record
    self.save_recording()
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 83, in save_recording
    recording_np = np.concatenate(np.array(self.recording, dtype=object), axis=0)
RuntimeError: Inconsistent object during array creation? Content of sequences changed (length inconsistent).
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
Process Process-3:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/thermal.py", line 85, in captureImages
    frame = self.camera.grab()  # .astype(np.float32)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/flirpy/camera/lepton.py", line 158, in grab
    res, image = self.cap.read()
KeyboardInterrupt
/home/dis/trust-me-setup/startup_script.sh: line 54: Run: command not found
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  2792 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
Done
sre 11 sep 2024 18:20:05 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 10
Brio channel: 8
StreamCam channel: 0
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  5392 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
pet 20 sep 2024 07:15:17 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 4
Brio channel: 2
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@60.518] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@60.518] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@60.521] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ WARN:0@60.521] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@70.531] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@80.544] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@90.550] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@100.560] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@110.567] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@120.578] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@130.588] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@140.599] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@150.607] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@160.618] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@170.628] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@180.635] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@190.646] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@200.656] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@210.667] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@220.675] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@230.686] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@240.695] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@250.703] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@260.714] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@270.719] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@280.730] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@290.732] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@300.742] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@310.753] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@320.763] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@330.774] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@340.784] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@350.795] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@360.805] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@370.816] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@380.823] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@390.831] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@400.839] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
[ WARN:0@410.850] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
/home/dis/trust-me-setup/startup_script.sh: line 54: Run: command not found
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  2849 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
Done
pet 20 sep 2024 08:08:32 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 10
Brio channel: 8
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Process Process-2:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 70, in captureImages
    self.pipeline.stop()
RuntimeError: stop() cannot be called before start()
[ WARN:0@60.541] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video7): can't open camera by index
[ WARN:0@60.541] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.881] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video6): select() timeout.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
[ WARN:0@196.499] global cap_v4l.cpp:889 requestBuffers VIDEOIO(V4L2:/dev/video8): failed VIDIOC_REQBUFS: errno=19 (No such device)
Process Process-1:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 81, in record
    self.save_recording()
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 91, in save_recording
    write(filename, self.sampling_rate, recording_np)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/scipy/io/wavfile.py", line 775, in write
    raise ValueError("Unsupported data type '%s'" % data.dtype)
ValueError: Unsupported data type 'object'
/home/dis/trust-me-setup/startup_script.sh: line 54: Run: command not found
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  5299 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
Done
pet 20 sep 2024 09:32:28 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 10
Brio channel: 8
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@60.501] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@60.501] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.790] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  4333 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
pet 20 sep 2024 09:56:38 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 10
Brio channel: 8
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@60.512] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@60.512] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
pet 20 sep 2024 10:02:25 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 10
Brio channel: 8
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@60.493] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video7): can't open camera by index
[ WARN:0@60.493] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Expression 'alsa_snd_pcm_start( stream->capture.pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2929
Expression 'AlsaStart( stream, 0 )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3241
Expression 'AlsaRestart( self )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3308
Expression 'PaAlsaStream_HandleXrun( self )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3934
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4269
Process Process-2:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 105, in captureImages
    frames = self.pipeline.wait_for_frames(10000)
RuntimeError: Frame didn't arrive within 10000
[ WARN:0@75.720] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video6): select() timeout.
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  3964 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
pet 20 sep 2024 10:13:04 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 10
Brio channel: 8
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@60.530] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@60.530] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.819] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
/home/dis/trust-me-setup/startup_script.sh: line 54: Run: command not found
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  2692 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
Done
pet 20 sep 2024 10:31:50 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 10
Brio channel: 8
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@30.515] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video5): can't open camera by index
[ WARN:0@30.516] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@41.809] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
Expression 'alsa_snd_pcm_start( stream->capture.pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2929
Expression 'AlsaStart( stream, 0 )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3241
Expression 'AlsaRestart( self )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3308
Expression 'PaAlsaStream_HandleXrun( self )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 3934
Expression 'PaAlsaStream_WaitForFrames( stream, &framesAvail, &xrun )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 4269
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 7:  3308 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
pet 20 sep 2024 10:36:47 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 10
Brio channel: 8
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@30.492] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@30.492] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Process-3:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/thermal.py", line 85, in captureImages
    frame = self.camera.grab()  # .astype(np.float32)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/flirpy/camera/lepton.py", line 158, in grab
    res, image = self.cap.read()
KeyboardInterrupt
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
pet 20 sep 2024 10:42:15 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 10
Brio channel: 8
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@30.491] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@30.491] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@41.779] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
