pet 19 jul 2024 13:37:50 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 4
Brio channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.049] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.049] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 19 jul 2024 13:42:58 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.054] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video5): can't open camera by index
[ WARN:0@61.054] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.256] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 19 jul 2024 13:47:55 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 10
Brio channel: 8
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.052] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.052] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 19 jul 2024 14:02:43 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.080] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video5): can't open camera by index
[ WARN:0@61.080] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.273] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video4): select() timeout.
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
čet 25 jul 2024 10:10:43 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.076] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video5): can't open camera by index
[ WARN:0@61.076] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
WARNING:flirpy.camera.lepton:Failed to capture image
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
čet 25 jul 2024 14:22:41 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.032] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video5): can't open camera by index
[ WARN:0@61.032] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 26 jul 2024 13:08:33 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 4
Brio channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.048] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.048] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 203, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 179, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pon 02 sep 2024 12:33:18 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
Brio channel: 12
Brio channel: 10
StreamCam channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.531] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.531] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 104, in captureImages
    with h5py.File(
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/h5py/_hl/files.py", line 241, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 122, in h5py.h5f.create
FileNotFoundError: [Errno 2] Unable to synchronously create file (unable to open file: name = 'installers/data_collection/data/realsense/depth/dis_0_2024-09-02$12-38-07-357544.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  5101 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
pon 02 sep 2024 14:12:58 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 12
Brio channel: 10
Brio channel: 8
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.021] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video7): can't open camera by index
[ WARN:0@61.021] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.335] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video6): select() timeout.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
/home/dis/trust-me-setup/installers/data_capture/microphone.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  recording_np = np.concatenate(np.array(self.recording), axis=0)
Process Process-1:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 79, in record
    self.save_recording()
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 83, in save_recording
    recording_np = np.concatenate(np.array(self.recording), axis=0)
RuntimeError: Inconsistent object during array creation? Content of sequences changed (length inconsistent).
/home/dis/trust-me-setup/startup_script.sh: line 62: Run: command not found
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  3286 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
Done
čet 05 sep 2024 07:12:38 CEST
conda 24.4.0
Video now available. Starting script...
StreamCam channel: 12
Brio channel: 10
Brio channel: 8
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@60.988] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video7): can't open camera by index
[ WARN:0@60.988] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.298] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video6): select() timeout.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Process-1:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 79, in record
    self.save_recording()
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 83, in save_recording
    recording_np = np.concatenate(np.array(self.recording, dtype=object), axis=0)
RuntimeError: Inconsistent object during array creation? Content of sequences changed (length inconsistent).
/home/dis/trust-me-setup/startup_script.sh: line 54: Run: command not found
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  3165 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
Done
čet 05 sep 2024 07:34:15 CEST
conda 24.4.0
Video now available. Starting script...
Brio channel: 12
Brio channel: 10
StreamCam channel: 0
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.012] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video3): can't open camera by index
[ WARN:0@61.012] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process Process-1:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 79, in record
    self.save_recording()
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 83, in save_recording
    recording_np = np.concatenate(np.array(self.recording, dtype=object), axis=0)
RuntimeError: Inconsistent object during array creation? Content of sequences changed (length inconsistent).
Process Process-3:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/thermal.py", line 85, in captureImages
    frame = self.camera.grab()  # .astype(np.float32)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/flirpy/camera/lepton.py", line 158, in grab
    res, image = self.cap.read()
KeyboardInterrupt
/home/dis/trust-me-setup/startup_script.sh: line 54: Run: command not found
python: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
/home/dis/trust-me-setup/installers/tobii/run_tobii.sh: line 4:  3952 Aborted                 /home/$(whoami)/miniconda3/envs/tobii/bin/python run_tobii.py
Done
čet 05 sep 2024 07:50:37 CEST
conda 24.4.0
Video now available. Starting script...
StreamCam channel: 6
Brio channel: 4
Brio channel: 2
Started recording RGB
Started recording tobii
Streamdeck running
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
